language: node_js
node_js:
  - "0.10"

before_install:
  - npm install -g grunt-cli
  - npm install -g istanbul

# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js"